# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true
highlighter: rouge

# Setup
title:               'Denis M.'
tagline:             'Stuff about things'
description:         ''
url:                 http://denmil.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Denis M.
  url:               http://denmil.github.io
  email:             aaa@gmail.com

# Custom vars
version:             1.0.0
