# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true


# Setup
title:               'Denis M.'
tagline:             'Stuff about things'
description:         '

<div>Contact links: 
    <a href="https://github.com/denmil">DB</a>
    <a href="https://twitter.com/___dns"><i class="fa fa-twitter social-icons"></i></a>
    <a href=""><i class="fa fa-envelope social-icons"></i></a>
    <a href="https://github.com/denmil"><i class="fa fa-github social-icons"></i></a>
</div>

'

url:                 http://denmil.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Denis M.
  url:               http://denmil.github.io
  email:             aaa@gmail.com

# Custom vars
version:             1.0.0
